variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  PathToSolution: 'AsyncAwaitBestPractices.sln'
  PathToiOSAppCsproj: 'sample/HackerNews.iOS/HackerNews.iOS.csproj'
  PathToUITestsCsproj: 'sample/HackerNews.UITests/HackerNews.UITests.csproj'
  PathToAndroidAppCsproj: 'sample/HackerNews.Droid/HackerNews.Droid.csproj'
  PathToUnitTestsCsproj: 'src/AsyncAwaitBestPractices.UnitTests/AsyncAwaitBestPractices.UnitTests.csproj'
  PathToAsyncAwaitBestPracticesCsproj: 'src/AsyncAwaitBestPractices/AsyncAwaitBestPractices.csproj'
  PathToAsyncAwaitBestPracticesMVVMCsproj: 'src/AsyncAwaitBestPractices.MVVM/AsyncAwaitBestPractices.MVVM.csproj'

trigger:
  branches:
    include:
    - main
  tags:
    include:
    - '*'

pr:
  autoCancel: 'true'
  branches:
    include:
    - main

jobs:     
  - job: build_sample
    displayName: Build Xamarin.Forms Sample App
    pool:
      vmImage: windows-latest
    
    steps:
      - task: UseDotNet@2
        displayName: 'Use .Net Core SDK  7.0.x'
        inputs:
          version: '7.0.x'
          installationPath: '$(Agent.ToolsDirectory)'
          performMultiLevelLookup: true

      - task: NuGetToolInstaller@1
        displayName: 'Use NuGet'
        inputs:
          checkLatest: true

      - task: VSBuild@1
        displayName: 'Build Android App'
        inputs:
          solution: '$(PathToAndroidAppCsproj)'
          configuration: 'Release'
          msbuildArgs: '/restore'

      - task: VSBuild@1
        displayName: 'Build iOS App'
        inputs:
          solution: '$(PathToiOSAppCsproj)'
          configuration: 'Release'
          msbuildArgs: '/restore'

      - task: VSBuild@1
        displayName: 'Build UI Test Project'
        inputs:
          solution: '$(PathToUITestsCsproj)'
          configuration: 'Release'
          msbuildArgs: '/restore'

      - task: CopyFiles@2
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        inputs:
          SourceFolder: '$(system.defaultworkingdirectory)'
          Contents: '**\bin\$(BuildConfiguration)\**'
          TargetFolder: '$(build.artifactstagingdirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)'

  - job: build_test_library
    displayName: Build + Test Library
    pool:
      vmImage: windows-latest

    steps:
    - task: UseDotNet@2
      displayName: 'Use .Net Core SDK 2.1.x'
      inputs:
        version: ' 2.1.x'
        includePreviewVersions: true
        installationPath: '$(Agent.ToolsDirectory)'
        performMultiLevelLookup: true

    - task: UseDotNet@2
      displayName: 'Use .Net Core SDK 3..x'
      inputs:
        version: ' 3.0.x'
        installationPath: '$(Agent.ToolsDirectory)'
        performMultiLevelLookup: true

    - task: UseDotNet@2
      displayName: 'Use .Net Core SDK  6.0.x'
      inputs:
        version: ' 6.0.x'
        installationPath: '$(Agent.ToolsDirectory)'
        performMultiLevelLookup: true

    - task: UseDotNet@2
      displayName: 'Use .Net Core SDK  7.0.x'
      inputs:
        version: '7.0.x'
        installationPath: '$(Agent.ToolsDirectory)'
        performMultiLevelLookup: true

    - task: NuGetToolInstaller@1
      displayName: 'Use NuGet'
      inputs:
        checkLatest: true

    - task: DotNetCoreCLI@2
      displayName: 'Run Unit Tests'
      inputs:
        command: test
        projects: '$(PathToUnitTestsCsproj)'
        arguments: '-c   Release'

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder: '$(system.defaultworkingdirectory)'
        Contents: '**\bin\$(BuildConfiguration)\**'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'